// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Database.Migrations
{
    [DbContext(typeof(MotherloadContext))]
    [Migration("20181117162124_InitialUpgrade_Hotfixes")]
    partial class InitialUpgrade_Hotfixes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<string>("CPR")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(8);

                    b.Property<string>("Name");

                    b.HasKey("CPR");

                    b.ToTable("People");
                });
#pragma warning restore 612, 618
        }
    }
}
